apiVersion: v2
name: kube-agent
description: AI-powered Kubernetes assistant for Slack
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - kubernetes
  - slack
  - ai
  - devops
  - chatops
maintainers:
  - name: Mobula
    url: https://github.com/MobulaFi
